title: Helps for Devs
description: > # this means to ignore newlines until "baseurl:"
  Solutions to tricky tech trip ups.
permalink: ':title/'
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Trevor Ackerman
author-img: coffeecat.jpeg
about-author: I am a software engineer with a passion for simplicity
social-github: trevorackerman
social-linkedin: trevor-ackerman
social-email: trevorackerman.softdev@gmail.com

# Disqus
discus-identifier: 

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown

kramdown:

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
